/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

public class AppsTest {
    @Test public void testAppHasAGreeting() {
        Apps classUnderTest = new Apps();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
